services:

    # simple server ngnix
    web:
        image: garyclarke/php-framework-web
        volumes:
            - ./public:/var/www/html/public
        ports:
            - "80:80"

    # php application
    app:
        image: garyclarke/php-framework-app
        volumes:
            - .:/var/www/html
        
